config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: {in: 4..20}
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/_dashboard.html.erb
<section class="container" >

<p class="title h1 border-bottom pb3 text-center">HI <%= current_user.name %> 👋🏻 </p>
 <div class="row">


    <div class="col">
       <div class="row border-right ph4">
          <div class="col-3 ">
             <h3 class="h5"> My Project <span class="badges"><%#= @projects.count %></span></h3>
           </div>
            <div class= "col-3 ">
                <%= button_to new_project_path, class: "btn btn-primary" do%>
                <span class="glyphicon glyphicon-plus"></span>
                 <% end %>
            </div>
       </div>
       <hr />

       <% @projects.each do |project| %>
         <div class="border-bottom pb4">
            <P class="h4"><%= link_to project.name,project %></p>
            <p class="text-muted"> Created by: <%= project.user.name %></p>
          </div>
        <% end %>

    </div>


    <div class="col">
           <div class="row border-right ph4">
          <div class="col-3 ">
             <h3 class="h5"> My Teams <span class="badges"><%#= @teams.count %></span></h3>
           </div>
            <div class= "col-3 ">
                <%= button_to new_team_path, class: "btn btn-primary" do%>
                <span class="glyphicon glyphicon-plus"></span>
                 <% end %>
            </div>
       </div>

        <hr />
       
         <% @teams.each do |team| %>
         <div class="border-bottom pb4">
            <P class="h4"><%= link_to team.name,team %></p>
            <span class="text-muted"><%= safe_join(team.user.map {|user| user.name}, ' ,')  %></span>
          </div>
        <% end %>
    </div>


    <div class="col">

       <h3 class="h3">Activity</h3>
			<hr />
			<ul class="lists">
				<%= render_activities(@activities) %>
			</ul>
    </div>


 </div>
</section 

app/views/home/index.html.erb
<div class="container">
<% if user_signed_in? %>
 <%=  render 'dashboard' %>
   
<% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary  fixed-top">
    <div class="container">
      <a class="navbar-brand ">
      <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title h5 text-white">Projekt</h1>
        <% end  %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
           <% if user_signed_in? %>
         <ul class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          New
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li class="dropdown-item navdrop-link">  
          <%#=link_to 'Project', new_project_path, class:"dropdown-item" %>
        </li>
        <li class="dropdown-item navdrop-link">  
          <%#= link_to 'Team', new_team_path, class:"dropdown-item" %>
          </li>
        </div>
        </ul>

        <ul class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li class="dropdown-item navdrop-link">  
            <%= link_to "Edite profile ", edit_user_registration_path, class:"navbar-item" %>
            </li> 
            <li class="dropdown-item navdrop-link">  
            <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"navbar-link" %>
            </li>          
        </div>
        </ul>
   
       
        
          <% else %>
          <li>
          <%= link_to "LOG IN", new_user_session_path, class:"navbar-link text-white p-3 " %>
          </li>
          <li>
           <%= link_to "Sign up", new_user_registration_path, class:"navbar-link text-white "%>          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projekt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <%= render "layouts/header"%>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>